name: AP-Client-Docker-bungeecord

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag autoplug-client:bungeecord_$(date +%s) --build-arg PROXY_SERVER=1 --build-arg SERVER_SOFTWARE=bungeecord